### ISSUE TITLE
Option Loader defaults to local timezone (not HighCharts default behavior)

### ISSUE THREAD

**Issue by drakej** [ahmadsoe/ember-highcharts#133] opened 2018-02-22 16:53 UTC
I noticed that all charts using ember-highcharts default to the local timezone and offset it without any options or configuration on behalf of the chart. You can override it but it seems odd that this is being set.

Specifically on this file: https://github.com/ahmadsoe/ember-highcharts/blob/ed1f9c7247c43410c6a799da23d76533cebb1d5d/addon/utils/option-loader.js

Lines 27-29 are the problem since you're setting the offset to new Date().getTimezoneOffset() which means this now is local instead of UTC which is the result based on the HighCharts default of "undefined".

I did test setting it back to undefined in the app/highcharts-configs/applications.js for global overrides.

`defaultOptions.global = {timezoneoffset: undefined};`

That worked to go back to default behavior as a workaround.

**Comment by acorncom** [comment] 2018-02-27 19:38
@drakej believe this is a duplicate of https://github.com/ahmadsoe/ember-highcharts/issues/129 ?

**Comment by drakej** [comment] 2018-02-27 19:51
Yes that is correct. Sorry I thought I had done a better job looking through existing issues. Good catch :+1:

**Closed** 2018-02-27 19:51 UTC
